-- BASIC EXAMPLE
CREATE TABLE TRANSACTIONS (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ORDER_NO TEXT(10) NOT NULL,
	ORDER_DATE TEXT(30),
	LINE_NO TEXT(20),
	ITEM_NO TEXT(30),
	ITEM_DESCRIPTION TEXT(255),
	"SIZE" TEXT(10),
	QUANTITY INTEGER,
	UNIT_PRICE_EUR NUMERIC,
	UNIT_PRICE_FOREIGN NUMERIC,
	CURRENCY TEXT(3),
	EXCHANGE_RATE NUMERIC,
	SALESPERSON_NO TEXT(15),
	SALESPERSON_NAME TEXT(255),
	CUSTOMER_NO TEXT(15),
	CUSTOMER_NAME TEXT(255),
	COUNTRY_CODE TEXT(3)
);

-- ENHANCED EXAMPLE
CREATE TABLE PRODUCT (
	ITEM_NO TEXT(30) NOT NULL,
	ITEM_DESCRIPTION TEXT(255),
	"SIZE" TEXT(10) NOT NULL,
	UNIT_PRICE_EUR NUMERIC, 
  	PRIMARY KEY (ITEM_NO, "SIZE")
);

CREATE TABLE SALESPERSON (
	SALESPERSON_NO TEXT(15) NOT NULL PRIMARY KEY,
	SALESPERSON_NAME TEXT(255)
);

CREATE TABLE CUSTOMER (
	CUSTOMER_NO TEXT(15) NOT NULL PRIMARY KEY,
	CUSTOMER_NAME TEXT(255)
);

CREATE TABLE "ORDER" (
	ORDER_NO TEXT(10) NOT NULL PRIMARY KEY,
	ORDER_DATE TEXT(30),
	SALESPERSON_NO TEXT(15) NOT NULL,
	CUSTOMER_NO TEXT(15) NOT NULL,
	CURRENCY TEXT(3),
	EXCHANGE_RATE NUMERIC,
	COUNTRY_CODE TEXT(3),
  	FOREIGN KEY(SALESPERSON_NO) REFERENCES SALESPERSON(SALESPERSON_NO),
  	FOREIGN KEY(CUSTOMER_NO) REFERENCES CUSTOMER(CUSTOMER_NO)
);

CREATE TABLE ORDER_ITEM (
	ORDER_NO TEXT(10) NOT NULL,
	LINE_NO TEXT(20) NOT NULL,
	ITEM_NO TEXT(30) NOT NULL,
	"SIZE" TEXT(10) NOT NULL,
	QUANTITY INTEGER,
	UNIT_PRICE_EUR NUMERIC,
	UNIT_PRICE_FOREIGN NUMERIC,
  	PRIMARY KEY (ORDER_NO, LINE_NO),
  	FOREIGN KEY(ORDER_NO) REFERENCES "ORDER"(ORDER_NO),
  	FOREIGN KEY(ITEM_NO,"SIZE") REFERENCES PRODUCT(ITEM_NO,"SIZE")
);